### ISSUE TITLE
Hello, I have added the code. Support for I2C, SPI, UART now!

### ISSUE THREAD

**Issue by Bendikos** [felipegtralli/pn532#1]
Hello, I have added the code
https://github.com/Bendikos/pn532

**Comment by felipegtralli** [comment]
Hello!
Would it be possible for us to talk sometime? If you have a preferred way to discuss (like email or chat), let me know!

**Comment by Bendikos** [comment]
m19e2k67@foxmail.com
in here add my discord

**Comment by felipegtralli** [comment]
what is your discord username?

**Comment by Bendikos** [comment]
19e2k67#2487

**Comment by Bendikos** [comment]
https://discord.gg/ubBhqhrw

**Comment by Bendikos** [comment]
https://discord.gg/ubBhqhrw
